backend:
  name: github
  repo: damdej/topmontaza  
  branch: main

media_folder: slike
public_folder: /slike

collections:
  - name: galerija
    label: Galerija
    files:
      - name: galerija
        label: Slike po kategorijama
        file: galerija.json
        fields:
          - label: Kategorije
            name: kategorije
            widget: list
            fields:
              - { label: Naziv kategorije, name: naziv, widget: string }
              - label: Slike
                name: slike
                widget: list
                fields:
                  - { label: Slika, name: slika, widget: image }
                  - { label: Kratak opis slike, name: opis, widget: string, required: false }
